add_newline = false

[character]
success_symbol = '[âœ”](bold green)'
error_symbol = '[âœ˜](bold red)'

[conda]
format = ' \[[$symbol$environment]($style)\]'
ignore_base = false
symbol = "ï„Œ "
style = 'bold yellow'

[cmd_duration]
format = ' \[[â± $duration]($style)\]'

# [battery]
# full_symbol = 'ğŸ”‹ '
# charging_symbol = 'âš¡ï¸ '
# discharging_symbol = 'ğŸ’€ '
#format = '\[[$symbol$percentage]($style)\]'

# [[battery.display]]
# threshold = 100
# style = 'bold yellow'

[time]
disabled = false
# Hour:Minute Format
time_format = "%R"
format = '\[[ïº $time]($style)\] '

[directory]
truncation_length = 20
truncate_to_repo = false
style = "cyan bold"
format = "[:$path]($style)[$read_only]($read_only_style) "

[memory_usage]
format = ' \[[$symbol$ram | $ram_pct]($style)\]'
style = 'bold yellow'
symbol = "ó°› "
threshold = 1
disabled = false

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = "îˆµ "

[docker_context]
format = '\[[$symbol$context]($style)\]'
symbol = "ïŒˆ "

[git_branch]
format = ' \[[$symbol$branch]($style)\]'
symbol = "ï˜ "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[java]
format = '\[[$symbol($version)]($style)\]'
symbol = "î‰– "

[sudo]
format = '\[[as $symbol]($style)\]'

[username]
format = '\[[$user]($style)\]'
